version: '3.8'

services:

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: musicapp-es
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=sonora-cluster
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: musicapp-logstash

    command: >
      bash -c "
              export LS_JAVA_OPTS='-Xmx512m -Xms512m' && \
              if ! bin/logstash-plugin list | grep -q 'logstash-filter-multiline'; then
                echo 'Installing logstash-filter-multiline plugin...' && \
                bin/logstash-plugin install logstash-filter-multiline;
              fi && \
              logstash -f /usr/share/logstash/pipeline/logstash.conf --path.settings /usr/share/logstash/config
            "
    volumes:
      - ./logstash-config/pipeline:/usr/share/logstash/pipeline
      - ./logstash-config/config:/usr/share/logstash/config
      - logstash-data:/usr/share/logstash/data
      - ./src/main/resources/musicapp-template.json:/usr/share/logstash/templates/musicapp-template.json
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      - XPACK_MONITORING_ENABLED=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LS_JAVA_OPTS=-Xmx256m -Xms512m
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: musicapp-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy


volumes:
  es-data:
  logstash-data:

networks:
  default:
    driver: bridge