version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: musicapp-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: eventomusical
      MYSQL_USER: musicuser
      MYSQL_PASSWORD: musicpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p1234"]
      interval: 5s
      timeout: 10s
      retries: 5

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: musicapp-es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Logstash
  logstash:
    image: logstash:8.12.0
    container_name: musicapp-logstash
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf --path.settings /usr/share/logstash/config
    volumes:
      - ./logstash-config/pipeline:/usr/share/logstash/pipeline
      - ./logstash-config/config:/usr/share/logstash/config
      - ./logs:/usr/share/logstash/data
      - ./src/main/resources/musicapp-template.json:/usr/share/logstash/templates/musicapp-template.json
    ports:
      - "5044:5044"
    environment:
      - XPACK_MONITORING_ENABLED=false
    depends_on:
      elasticsearch:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q 'logstash' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: musicapp-backend
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/eventomusical?useSSL=false
      - SPRING_DATASOURCE_USERNAME=musicuser
      - SPRING_DATASOURCE_PASSWORD=musicpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=your_jwt_secret_here
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_USERNAME=your_email@gmail.com
      - SPRING_MAIL_PASSWORD=your_app_password
    volumes:
      - ./target:/app/target
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      logstash:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql-data:
  es-data: