version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: eventomusical-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: eventomusical

    ports:
      - "3307:3306"
    volumes:
      - eventomusical-db-data:/var/lib/mysql

    networks:
      - eventomusical-network

  sync-service:
    image: alpine
    container_name: db-sync
    depends_on:
      - db
    volumes:
      - ./sync-scripts:/scripts
    networks:
      - eventomusical-network
    command: >
      sh -c "
      apk add --no-cache mysql-client bash &&
      while ! nc -z db 3306; do sleep 1; done &&
      while true; do
        mysql -h host.docker.internal -u root -p1234 --port=3306 eventomusical -e 'FLUSH TABLES WITH READ LOCK; SYSTEM mysqldump -u root -p1234 --port=3306 eventomusical > /tmp/dump.sql; UNLOCK TABLES;' &&
        mysql -h db -u root -p1234 eventomusical < /tmp/dump.sql &&
        sleep 60
      done"

volumes:
  eventomusical-db-data:

networks:
  eventomusical-network:
    driver: bridge