version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: eventomusical-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: eventomusical
    ports:
      - "3307:3306"
    volumes:
      - eventomusical-db-data:/var/lib/mysql
    networks:
      - eventomusical-network

volumes:
  eventomusical-db-data:

networks:
  eventomusical-network:
    driver: bridge